services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ahun_members_service'
      - 'POSTGRES_PASSWORD=ahun'
      - 'POSTGRES_USER=ahun'
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/postgresql/data

volumes:
  pg_data:
