[versions]
springBoot = "3.3.5"
springDependencyManagement = "1.1.7"
springCommonsWeb = "2.4.0"
commonsTelegramBot = "1.0.0"

[libraries]
petrolal-commons-web = { module = "com.petrolal.commons.web:spring-commons-web", version.ref = "springCommonsWeb" }
petrolal-commons-telegram = { module = "com.petrolal.commons.telegram:commons-telegram", version.ref = "commonsTelegramBot" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
