[versions]
springBoot = "3.3.5"
springDependencyManagement = "1.1.7"
springCommonsWeb = "2.4.0"
telegrambotsSpringBootStarter = "6.9.7.1"

[libraries]
petrolal-commons-web = { module = "com.petrolal.commons.web:commons-web", version.ref = "springCommonsWeb" }
telegrambots-spring-boot-starter = { module = "org.telegram:telegrambots-spring-boot-starter", version.ref = "telegrambotsSpringBootStarter" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
